### ISSUE TITLE
chartist won't draw after ajax success

### ISSUE THREAD

**Issue by squarer** [fundon/vue-admin#10]
I'm trying to set chartist data from ajax:
```
<div class="tile is-parent">
  <article class="tile is-child box">
    <h4 class="title">Chart</h4>
    <div class="block">
      <chartist class="lines-bars" :type="'Line'" :data="lineAreaData" :options="lineAreaOptions"></chartist>
    </div>
  </article>
</div>
```

```
methods: {
  setChart () {
    $.ajax({
      url: 'url'
      type: 'GET',
      success: function (ret) {
        this.lineAreaData.series[0] = ret
      }.bind(this),
      error: function (xhr, status, err) {
        console.error('url', status, err.toString())
      }
    })
  }
},

ready () {
  this.setChart()
}
```
I've checked `this.lineAreaData.series` has been set as I expect in ajax success event,
but chartist won't refresh until resize browser, any suggestion will be appreciated, thx!

**Comment by fundon** [comment]
You should use `() => {}` arrow function instead of `function () {}`.

Because  `this.lineAreaData.series[0] = ret` the scope of  `this`  is not current component.

**Comment by squarer** [comment]
@fundon 
thx for your quick response! I try out arrow function but not work,
the chart not draw when page launch, but do work when I manually resize browser window.

**Comment by fundon** [comment]
@squarer I found the point.

See http://vuejs.org/api/#Array-Extension-Methods and http://vuejs.org/guide/list.html#Mutation-Methods.

So you can try this:

```js
this.lineAreaData.series[0].splice(0)
this.lineAreaData.series.push(...ret)
```

**Comment by fundon** [comment]
I will fix the bug. The `this.lineAreaData` is a deep object.

**Comment by squarer** [comment]
thanks for your help, I'll look into the documents
