### ISSUE TITLE
Live demo error

### ISSUE THREAD

**Issue by icebob** [fundon/vue-admin#2]
the https://vue-admin.fundon.me site on Chrome v50.0.2661.102 m gives error:

vendor.47929fa358fbcd2b8725.js:2 Uncaught SyntaxError: missing ) after argument list
manifest.7a8aaf8….js:1 Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by fundon** [comment]
@icebob  Thanks for your report.
I'm updating the gh-pages.
Done, now!.

Force reload the page.

**Comment by icebob** [comment]
I reloaded with CTRL+F5, checked not load from cache, but the same error

**Comment by fundon** [comment]
Use the `http`, try this http://vue-admin.fundon.me/.

**Comment by icebob** [comment]
Ok, it's working. Thanks!
