### ISSUE TITLE
DatePicker data binding?

### ISSUE THREAD

**Issue by martinhearn** [fundon/vue-admin#21]
How do I add binding to the datepicker component?
Neither v-model="item.start_date" nor :v-bind:value="item.start_date" work as it's a fragment instance and value="item.start_date" populates but doesn't sync...
Sorry there's probably an obvious answer to this that I have overlooked...Thanks!

**Comment by Dennisoost** [comment]
Not the creator, but try :value.sync="item.start_date"

[https://vuejs.org/guide/components.html#Prop-Binding-Types](url)

**Comment by martinhearn** [comment]
thanks @dennisoost I tried that too, no difference. It populates but doesn't sync.
I've also added `twoWay: true` to the `value` prop but that didn't make any difference either.

**Comment by Dennisoost** [comment]
@martinhearn 
I took a look at the code, and i doubt it's even possible atm. 

To me it seems like flatpickr is called in the ready () function. The datepicker has a 1 time initialization with the value="" property.

**Comment by martinhearn** [comment]
thanks @Dennisoost you have led me in the right direction, I solved it by adding:
```
 this.datepicker.set('onChange', (d, s) => {
     this.$set('value', s)
    })
```
`s` is the formatted date.

I have submitted a pull request.

**Comment by fundon** [comment]
Thank you. 👍 

Merged in https://github.com/fundon/vue-admin/pull/22
