### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by decebal** [fundon/vue-admin#25]

**Comment by fundon** [comment]
Need more details. Thanks.

**Comment by decebal** [comment]
I git cloned the project into a new folder, ran npm install and gives me that error from the start .

**Comment by fundon** [comment]
try `npm rebuild -d`

**Comment by xchz** [comment]
`E:\admin\vue-admin-0.1.12>npm install
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the
'mapbox-gl-style-spec' package
npm WARN deprecated mapbox-gl-function@1.3.0: This package has been merged with
the 'mapbox-gl-style-spec' package
npm WARN deprecated vector-tile@1.3.0: This module is now under the @mapbox name
space: install @mapbox/vector-tile instead
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox nam
espace: install @mapbox/geojson-area instead
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using
chalk, upgrade to the latest version. https://github.com/chalk/supports-color
npm ERR! cb() never called!`

**Comment by xchz** [comment]
i have try npm rebuild -d...

**Comment by xchz** [comment]
i upgrade nodev5.9.1--->v6.2.0, it works!
