### ISSUE TITLE
Bugs with Datepicker

### ISSUE THREAD

**Issue by JeOam** [fundon/vue-admin#26]
click Basics Datepicker on: https://vue-admin.fundon.me/#!/components/datepicker, while clicking  input fields one by one downward, got the following picture easily.

<img width="525" alt="screen shot 2016-07-15 at 11 06 47 am" src="https://cloud.githubusercontent.com/assets/1294533/16862487/7680c576-4a7c-11e6-89cf-b367fe99b2ae.png">

**Comment by fundon** [comment]
Good Catch! 

I tested it and it's really bug.

**Comment by fundon** [comment]
Related to https://github.com/chmln/flatpickr/issues/181.

**Comment by JeOam** [comment]
@fundon btw, while using vue-bulma-datepicker with `:config="{ static: true}"` option,  this [line](https://github.com/vue-bulma/datepicker/blob/master/src/Datepicker.vue#L41) of code would cause `Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node'` error if you  tried to jump to another page

**Comment by fundon** [comment]
@JeOam Fixed.

> @fundon btw, while using vue-bulma-datepicker with :config="{ static: true}" option, this line of code would cause Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node' error if you tried to jump to another page

**Comment by JeOam** [comment]
@fundon cool! 👍

**Comment by fundon** [comment]
@JeOam Flatpickr is fixed it, so closed it.
