### ISSUE TITLE
Bug with *LevelBar*

### ISSUE THREAD

**Issue by zhuwei05** [fundon/vue-admin#27]
In LevelBar.vue, if the menu's label and link are different, the *breadcrumb* is wrong, see here: [The breadcrum just show **Home**](https://vue-admin.fundon.me/#!/tables/basic)

I think the code can fix : 
```
// Levelbar.vue
methods: {
  find(name, list) {
  ...
  if (item.label === name || item.link === name) {
...
```

**Comment by fundon** [comment]
Thank to your feedback.

Could you post a PR?
