### ISSUE TITLE
webpack.base.conf.js windows problem

### ISSUE THREAD

**Issue by fluxin** [fundon/vue-admin#29]
Putting in the regex to include vue-bulma does not work on windows. 
Using 
`node_modules\\' + path.sep + '(?!vue-bulma-).*`
does work though

**Comment by fundon** [comment]
Good catch! Thanks.

**Comment by fundon** [comment]
@fluxin try this `new RegExp(`node_modules\\${path.sep}\(\?\!\(vue-bulma-.*\)\)`)`
