### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by j0sephandres1987** [fundon/vue-admin#34]
i installed via npm, how do i use in my vuejs app?

**Comment by fundon** [comment]
Currently, it is not pushed the latest version to NPM, so we need `git-clone` it to local.

If you want to use it to your project. Maybe you need [vue-bulma](https://github.com/vue-bulma).

Vue Admin is based on Vue bulma.

**Comment by j0sephandres1987** [comment]
:(

**Comment by j0sephandres1987** [comment]
https://www.npmjs.com/package/vue-admin

**Comment by fundon** [comment]
Yes, https://www.npmjs.com/package/vue-admin is my project, but  I don't publish the latest source codes to NPM.

**Comment by j0sephandres1987** [comment]
ok, thanks

**Comment by vernard** [comment]
I guess it's because it is still WIP. In my opinion it would still be useful to be able to pull this using npm. But we'll have to wait for a major release

**Comment by fundon** [comment]
v0.1.0 is released. https://www.npmjs.com/package/vue-admin
