### ISSUE TITLE
Charts not fully responsive

### ISSUE THREAD

**Issue by Mat-thieu** [fundon/vue-admin#37]
I believe this only applies to ChartJS charts, first visit a page with charts, then navigate to any other page and resize it, then navigate back and all the charts seem skewed.

Tested in Chrome

**Comment by fundon** [comment]
Thanks, could you post a PR?

I will continue to focus this on **next** branch (with Vue 2.0).

**Comment by fundon** [comment]
@Mat-thieu It's still exists on next branch?
