### ISSUE TITLE
Components/Levelbar.vue 

### ISSUE THREAD

**Issue by onthedesk** [fundon/vue-admin#40]
不好意思，一个简单的拼写错误，我就不发pull request了，感谢fundon的辛勤劳动，我们正在使用，后续希望可以贡献代码。

src/components/Levelbar.vue Line:68

             if (item.subMenu) {
          if (item.link) {
            temp.push({
              lable: item.label,// lable => label
              link: item.link
            })

**Comment by fundon** [comment]
Good!

Master 就不会有新功能开发了，现在精力都会在 Vue 2.0 上。

欢迎贡献！ 👍
