### ISSUE TITLE
npm run dev bug

### ISSUE THREAD

**Issue by makenum** [fundon/vue-admin#44]
ERROR in ./client/App.vue
Module not found: Error: Can't resolve 'vue-style-loader' in 'D:\GitHub\vue-admin\client'
 @ ./client/App.vue 4:0-163
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./client/components/layout/Navbar.vue
Module not found: Error: Can't resolve 'vue-style-loader' in 'D:\GitHub\vue-admin\client\components\layout'
 @ ./client/components/layout/Navbar.vue 4:0-166
 @ ./client/components/layout/index.js
 @ ./~/.npminstall/babel-loader/6.2.5/babel-loader!./~/.npminstall/vue-loader/9.3.2/vue-loader/lib/selector.js?type=script&index=0!./client/App.vue
 @ ./client/App.vue
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./client/components/layout/Sidebar.vue
Module not found: Error: Can't resolve 'vue-style-loader' in 'D:\GitHub\vue-admin\client\components\layout'
 @ ./client/components/layout/Sidebar.vue 4:0-167
 @ ./client/components/layout/index.js
 @ ./~/.npminstall/babel-loader/6.2.5/babel-loader!./~/.npminstall/vue-loader/9.3.2/vue-loader/lib/selector.js?type=script&index=0!./client/App.vue
 @ ./client/App.vue
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./client/components/layout/Main.vue
Module not found: Error: Can't resolve 'vue-style-loader' in 'D:\GitHub\vue-admin\client\components\layout'
 @ ./client/components/layout/Main.vue 4:0-164
 @ ./client/components/layout/index.js
 @ ./~/.npminstall/babel-loader/6.2.5/babel-loader!./~/.npminstall/vue-loader/9.3.2/vue-loader/lib/selector.js?type=script&index=0!./client/App.vue
 @ ./client/App.vue
 @ ./client/app.js
 @ ./client/index.js
 @ multi app
webpack: bundle is now VALID.

**Comment by fundon** [comment]
What's versions of your NPM and Node.js?

**Comment by makenum** [comment]
Node.js 6.3.1 
NPM 3.10.5

**Comment by fundon** [comment]
@makenum Do you execute `npm install`?

**Comment by Charlie5422** [comment]
I got the same errors
OS platform: Ubuntu 16.04 LTS

WARNING in ./~/.3.9.3@node-sass/lib/index.js
23:14 Critical dependency: the request of a dependency is an expression

ERROR in multi vendor
Module not found: Error: Can't resolve 'font-awesome' in '/home/charlie/projects/vue-admin'
 @ multi vendor

ERROR in ./~/.0.1.2@bulma/bulma.sass
Module parse failed: /home/charlie/projects/vue-admin/node_modules/.0.1.2@bulma/bulma.sass Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "utf-8"
| 
| @import "sass/utilities/utilities"
 @ multi vendor

ERROR in ./~/.1.7.22@mdi/preview.html
Module parse failed: /home/charlie/projects/vue-admin/node_modules/.1.7.22@mdi/preview.html Unexpected token (1:1)
You may need an appropriate loader to handle this file type.
| ﻿<!doctype html>
| <html>
| <head>
 @ multi vendor

ERROR in ./~/.4.0.2@sass-loader/index.js
Module not found: Error: Can't resolve 'fs' in '/home/charlie/projects/vue-admin/node_modules/.4.0.2@sass-loader'
 @ ./~/.4.0.2@sass-loader/index.js 7:9-22
 @ multi vendor
……
……blablabla

**Comment by fundon** [comment]
Related to https://github.com/fundon/vue-admin/issues/39.
