### ISSUE TITLE
很多组件没有看到使用文档，比如Collapse这个组件该怎么使用？

### ISSUE THREAD

**Issue by JerroldLee** [fundon/vue-admin#46]
很多组件没有看到使用文档，比如Collapse这个组件该怎么使用？

**Comment by fundon** [comment]
组件都放在 [vue-bulma](https://github.com/vue-bulma)，文档也在补充

**Comment by luckylucy1233** [comment]
是啊，求使用文档啊

**Comment by fundon** [comment]
@luckylucy1233 这周会完善这块

**Comment by fundon** [comment]
@JerroldLee `Collapse` 文档已更新 https://github.com/vue-bulma/collapse。
