### ISSUE TITLE
国内浏览器兼容性问题

### ISSUE THREAD

**Issue by harryyuanfeng** [fundon/vue-admin#49]
请问有没有测试过国内浏览器的兼容性哦？UI很漂亮，不过就是担心兼容性

**Comment by fundon** [comment]
目前只支持标准浏览器，其他的如果有问题可以提交 PR。谢谢。

**Comment by harryyuanfeng** [comment]
标准浏览器指的是？

**Comment by fundon** [comment]
* Chrome
* Edge
* Firefox
* Internet Explorer (10+)
* Opera
* Safari

**Comment by pet1330** [comment]
@fundon I have tried this out in Internet Explorer 11 and it does not appear to be working:


![ie11](https://cloud.githubusercontent.com/assets/4920245/21944971/b846a8de-d9d0-11e6-99d2-5a9ecede7d67.png)


![ie11-status](https://cloud.githubusercontent.com/assets/4920245/21944972/b8492366-d9d0-11e6-853e-a184e0a87ad6.png)
