### ISSUE TITLE
tabs下面使用表格时候表格样式乱掉了.

### ISSUE THREAD

**Issue by sukui** [fundon/vue-admin#55]
tabs下面使用表格时候表格样式乱掉了.
请问这种有办法解决么、

**Comment by fundon** [comment]
有更详细的用例代码吗？

**Comment by sukui** [comment]
`<tabs size="medium">
  <tab-pane label="Account">
    <div class="table-responsive">
      <table class="table is-bordered is-striped is-narrow">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Spend</th>
            <th>Order Num</th>
            <th colspan="3">Option</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <label class="checkbox">
                <input type="checkbox" value={{ item.campaign_id }}>
              </label>
            </td>
            <td>
              <a href="#">test</a>
            </td>
            <td>10</td>
            <td>100</td>
            <td class="is-icon">
              <a href="#"><i class="fa fa-github"></i></a>
            </td>
            <td class="is-icon">
              <a href="#"><i class="fa fa-twitter"></i></a>
            </td>
            <td class="is-icon">
              <a href="#"><i class="fa fa-globe"></i></a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </tab-pane>
  <tab-pane label="Campaign2">
    Campaign2
  </tab-pane>
</tabs>`

麻烦了.  tabs 重定义了 a 的样式

**Comment by fundon** [comment]
@sukui 有截图吗？我看了下没发现什么问题。

**Comment by sukui** [comment]
@fundon vue 1.0 的版本错误. 不过没关系了，着手升级2.0

**Comment by fundon** [comment]
好，还有问题，重新打开这个  issue。
