### ISSUE TITLE
[npm run dev] throw new WebpackOptionsValidationError

### ISSUE THREAD

**Issue by leinue** [fundon/vue-admin#56]
> vue-admin@0.0.1 dev /private/var/www/apache/gospel/admin
> node build/server.js

/private/var/www/apache/gospel/admin/node_modules/.2.1.0-beta.25@webpack/lib/webpack.js:16
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           vue: ...
         }
       })
     }
 - configuration.resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/private/var/www/apache/gospel/admin/node_modules/.2.1.0-beta.25@webpack/lib/webpack.js:16:9)
    at Object.<anonymous> (/private/var/www/apache/gospel/admin/build/server.js:9:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! vue-admin@0.0.1 dev: `node build/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-admin@0.0.1 dev script 'node build/server.js'.
npm ERR! This is most likely a problem with the vue-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vue-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/www/apache/gospel/admin/npm-debug.log

**Comment by leinue** [comment]
这个ui用的node版本是什么

**Comment by fundon** [comment]
目前我用 node *v6.5.0*.  Webpack 更新到了最新的 beta，会对配置文件进行检查（要注意）。

`node build/server.js` => `npm run dev`

**Comment by leinue** [comment]
我用的osx

**Comment by leinue** [comment]
刚才我升级到了v6.6.0 还是一样的错误 好像是webpack2.0的问题？

**Comment by fundon** [comment]
现在 `build` 目录没有 `build/server.js` 文件，请把 vue-admin 更新到最新，再执行 `npm run dev`

**Comment by fundon** [comment]
如果还有问题，请重新打开。

**Comment by leinue** [comment]
我是刚clone的，有server.js

**Comment by fundon** [comment]
没有哦 https://github.com/fundon/vue-admin/tree/next/build

**Comment by leinue** [comment]
xieyang-2:build xieyang$ ls
index.html	server.js	webpack.base.js	webpack.dev.js	webpack.prod.js
xieyang-2:build xieyang$ pwd
/var/www/apache/gospel/admin/build

亲 真的有啊

**Comment by leinue** [comment]
我再重新clone下

**Comment by leinue** [comment]
ERROR in ./client/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.0-rc.6
- vue-template-compiler@2.0.0-rc.7

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

**Comment by leinue** [comment]
很多类似的错误 我从新clone的

**Comment by leinue** [comment]
我还没找到解决办法 这一上午打扰了

**Comment by fundon** [comment]
刚我也遇到了，把 `vue-template-compiler` 和 `vue` 都更新到 `2.0.0-rc.7` 可以解决。

**Comment by fundon** [comment]
> 我还没找到解决办法 这一上午打扰了

@leinue ，欢迎交流，欢迎 PR！ 😄

**Comment by leinue** [comment]
抱歉，又报错了……

ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

**Comment by fundon** [comment]
`npm update`

**Comment by leinue** [comment]
还是错……

ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-emoji/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-emoji/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
| 
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-progress-tracker/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
| 
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 74:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app
