### ISSUE TITLE
[npm run dev]You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by leinue** [fundon/vue-admin#57]
xieyang-2:admin xieyang$ cnpm run dev

> gospel-admin@0.0.1 dev /private/var/www/apache/gospel/admin
> node build/dev-server.js

server started at localhost:8080
webpack: wait until bundle finished: /
webpack: wait until bundle finished: /
webpack built 23d395279e5d00bea362 in 33427ms
Hash: 23d395279e5d00bea362
Version: webpack 2.1.0-beta.25
Time: 33427ms
                                                           Asset     Size  Chunks       Chunk Names
                           fonts/fontawesome-webfont.ttf?1dc35d2   153 kB               
materialdesignicons-webfont.svg?8b3c39c92337731eed918959d2abee5f  1.86 MB               
                   fonts/materialdesignicons-webfont.eot?d5247f9   246 kB               
                   fonts/materialdesignicons-webfont.ttf?3daf0ea   246 kB               
                 fonts/materialdesignicons-webfont.woff2?85f0bd2  93.9 kB               
                  fonts/materialdesignicons-webfont.woff?6f612b8   122 kB               
                           fonts/fontawesome-webfont.eot?25a3241  76.5 kB               
        fontawesome-webfont.svg?d7c639084f684d66a1bc66855d193ed8   392 kB               
                         fonts/fontawesome-webfont.woff2?e6cf7c6  71.9 kB               
                          fonts/fontawesome-webfont.woff?c8ddf1e  90.4 kB               
                                                          app.js  7.48 MB       0       app
                                                       vendor.js   278 kB       1       vendor
                                                      app.js.map   9.3 MB       0       app
                                                   vendor.js.map   343 kB       1       vendor

ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-emoji/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-emoji/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
| 
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-progress-tracker/src/index.js
Module parse failed: /private/var/www/apache/gospel/admin/node_modules/.0.0.1@vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
| 
 @ ./~/.6.2.5@babel-loader!./~/.9.5.0@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 74:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  559 kB       0       
webpack: bundle is now VALID.

**Comment by leinue** [comment]
xieyang-2:admin xieyang$ node -v
v6.6.0
xieyang-2:admin xieyang$ npm -v
3.10.3
xieyang-2:admin xieyang$ cnpm -v
4.3.2

**Comment by fundon** [comment]
建议把下面的更新到最新，或者 `rm -rf node_modules && npm install -d`
```js
    "vue-bulma-breadcrumb": "github:vue-bulma/breadcrumb",
    "vue-bulma-chartist": "github:vue-bulma/chartist",
    "vue-bulma-chartjs": "github:vue-bulma/chartjs",
    "vue-bulma-collapse": "github:vue-bulma/collapse",
    "vue-bulma-datepicker": "github:vue-bulma/datepicker",
    "vue-bulma-emoji": "github:vue-bulma/emoji",
    "vue-bulma-expanding": "github:vue-bulma/expanding",
    "vue-bulma-jump": "github:vue-bulma/jump",
    "vue-bulma-message": "github:vue-bulma/message",
    "vue-bulma-modal": "github:vue-bulma/modal",
    "vue-bulma-notification": "github:vue-bulma/notification",
    "vue-bulma-progress-bar": "github:vue-bulma/progress-bar",
    "vue-bulma-progress-tracker": "github:vue-bulma/progress-tracker",
    "vue-bulma-rating": "github:vue-bulma/rating",
    "vue-bulma-slider": "github:vue-bulma/slider",
    "vue-bulma-tooltip": "github:vue-bulma/tooltip",
    "vue-cleave": "github:vue-bulma/cleave",
    "vue-handsontable": "github:vue-bulma/handsontable",
    "vue-nprogress": "github:vue-bulma/nprogress",
    "vue-peity": "github:vue-bulma/peity",
```

**Comment by leinue** [comment]
成功了，感谢
