### ISSUE TITLE
Upgrade to Vue 2.0

### ISSUE THREAD

**Issue by fundon** [fundon/vue-admin#6]
# Vue Bulma Components

* [x]  vue-bulma-breadcrumb

* [x]  vue-bulma-chartist

* [x]  vue-bulma-chartjs

* [x]  vue-bulma-collapse

* [x]  vue-bulma-datepicker

* [x]  vue-bulma-emoji

* [x]  vue-bulma-jump

* [x]  vue-bulma-message

* [x] vue-bulma-modal

* [x]  vue-bulma-notification

* [x]  vue-bulma-progress-bar

* [x]  vue-bulma-progress-tracker

* [x]  vue-bulma-rating

* [x]  vue-bulma-slider

* [x]  vue-bulma-switch

* [x]  vue-bulma-tabs

* [x]  vue-bulma-tooltip

* [x]  vue-cleave

NOTES:

https://github.com/vuejs/vue/issues/2873
https://github.com/vuejs/vuejs.org/tree/2.0/src/guide

**Comment by chekun** [comment]
Do you have  ETA?

**Comment by fundon** [comment]
Waiting for Vue 2.o is released.

**Comment by fundon** [comment]
Working in https://github.com/fundon/vue-admin/tree/next
