### ISSUE TITLE
日期控件同时使用Inline or embedded calendar和Display week numbers时，样式混乱

### ISSUE THREAD

**Issue by romisanic** [fundon/vue-admin#60]
在demo地址测试日期控件：
https://vue-admin.fundon.me/components/datepicker

在Display week numbers点击打开日期控件时，会与上一行的Inline or embedded calendar产生冲突。如下图：
![date_picker](https://cloud.githubusercontent.com/assets/3611436/18861326/011ff1d8-84b7-11e6-8a55-e58a89dacee8.png)

**Comment by fundon** [comment]
谢谢反馈，您用的是什么浏览器以及版本多少？

**Comment by fundon** [comment]
如果还有这个问题，请重新打开，谢谢。

**Comment by romisanic** [comment]
Chrome 版本 46.0.2490.71 (64-bit)
相同的现象
