### ISSUE TITLE
npm run dev 报错。vue 版本兼容问题？

### ISSUE THREAD

**Issue by fomenyesu** [fundon/vue-admin#65]
你好，我下载了你的代码。npm install 后。安装完成，然后npm run dev 报错了。报错信息如下：

ERROR in ./client/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.0-rc.8
- vue-template-compiler@2.0.1

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

**Comment by fundon** [comment]
谢谢反馈

请看 https://github.com/fundon/vue-admin/issues/63。

1. 更新到最新的源代码，
2. 执行 `npm up -d` ，把包更新到最新
3. 再执行  `npm run dev`
