### ISSUE TITLE
[HELP] How to manipulate page name in the Levelbar

### ISSUE THREAD

**Issue by PhillippOhlandt** [fundon/vue-admin#69]
Hey,

right now, the Levelbar shows the route name. Is there a way to manipulate that? 
I have a `User` route with `/user/:id` as path and would like to show the received username instead.

**Comment by fundon** [comment]
See https://github.com/fundon/vue-admin/blob/master/client/components/layout/Levelbar.vue.

We can change the `name` getter method. or `getList()` method behaviour.

Which one do you want to manipulate? Left or right?

**Comment by PhillippOhlandt** [comment]
Hey,

would be nice to be able to override them both. The problem I see here is that the data I want to show gets loaded on my component, so it isn't available in the route definition.

**Comment by fundon** [comment]
We can define something on `route.meta` object.

```js
{
  name: 'User',
  path: '/users/:id',
  meta: {
    getName (route) {
       return route.params.id
   }
  }
}
```

And then

```js
    name () {
      return this.$route.meta.getName ? this.$route.meta.getName(this.$route) : this.$route.name
    }
```

**Comment by PhillippOhlandt** [comment]
Would work, but I want to display the name of the user and that is fetched via the API. Or can I override the meta info on the current route? I know it's possible to replace the whole route but that's not what we need.

**Comment by fundon** [comment]
Yes, meta could be overrided, and should use the vuex way.

**Comment by PhillippOhlandt** [comment]
That means? Storing the data in vuex when it's fetched and reading from vuex in the Levelbar component?

**Comment by fundon** [comment]
`menu` is already in store. See  https://github.com/fundon/vue-admin/blob/master/client/store/index.js#L4-L13.

**Comment by PhillippOhlandt** [comment]
Ah, good. Will test that tomorrow at work :)

**Comment by fundon** [comment]
@PhillippOhlandt What is the progress?

**Comment by PhillippOhlandt** [comment]
Hey,

I decided to do that sometime later and continue the port (from a react admin panel to this) for now.
