### ISSUE TITLE
[HELP]I wonder what happened?

### ISSUE THREAD

**Issue by cpprookie** [fundon/vue-admin#70]
I cloned the code to try to use vue,however i found some mistakes after  trying insert some `<script>` in conmponet which named Basic Table. I'm doing this to request messages from server for creating a table but i missed the linking component after inserting `<script>`. Would you please tell me what's wrong in my code? Thanks!

My code:
```
<template>
  <div>
    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <article class="tile is-child box">
          <h4 class="title">用户列表</h4>
          <table class="table">
            <thead>
              <tr>
                <th>用户编号</th>
                <th>用户名</th>
                <th>联系电话</th>
                <th>邮箱</th>
                <th><button>删除</button></th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="user in users">
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.phone }}</td>
                <td>{{ user.email }}</td>
                <td><button @click=>删除</button><td>
              </tr>
            </tbody>
          </table>
        </article>
      </div>
    </div>
  </div>
</template>

<script>
  export default{
    ready () {
      this.$http.post('http://127.0.0.1:38080/admin/api/v1/user/1/user?appKey=12')
        .then(function (ret) {
          this.users = ret.data.data
          return this.users
        })
    },

    data () {
      return {
        users: this.users
      }
    }
  }
</script>

<style lang="scss">
.table-responsive {
  display: block;
  width: 100%;
  min-height: .01%;
  overflow-x: auto;
}
</style>

```

**Comment by fundon** [comment]
Which version of vue?

Vue v2 should use `mounted` instead of `ready`.

**Comment by cpprookie** [comment]
@fundon 
My version is 1. 
It shouldn't be caused by vue vesion. Because i have made successful request from server when i trid to use `vue-resource`for the first time, and  created the  table with server response . But laterly i tried method `deleteUsers`, nothing appeared after linking conponent `Basic Table`. Worst thing is  that i will get a blank view even if i drop method `deleteUsers` . It seems like if i insert `<script>` then i will get a blank view when linking to conponent`Basic Table`.

**Comment by fundon** [comment]
You should use this way for fetching data. see https://github.com/vuejs/vue-router/blob/1.0/example/advanced/components/inbox/message.vue#L11-L51.

**Comment by cpprookie** [comment]
@fundon
Thanks  for  your  help.  But  it  seems  that  something  else  wrong.  After  i   solve  the  problem i  will   share  my solution.
Thanks   again!
