### ISSUE TITLE
[QUESTION] Dashboard demo

### ISSUE THREAD

**Issue by noncototient** [fundon/vue-admin#71]
What are you using for the loading animation and page loading/switching on the demo site here: https://vue-admin.fundon.me/dashboard

Really like the animation and how nice everything is, was hoping someone would be able to help me out please?

**Comment by fundon** [comment]
Vue Admin uses [vue-bulma/nprogress] component to trace loading/switching status.

**Comment by noncototient** [comment]
Thank you @fundon!
