### ISSUE TITLE
[HELP]How to link App after Login

### ISSUE THREAD

**Issue by cpprookie** [fundon/vue-admin#72]
Hello,Mr Cai. I'm here again to ask some help.
BTW, I solve my last trouble  by using sub-router and v-link,  Thanks for your advice again.
I meet new toubles when i want to create a  `LogIn`  conponent and **link to**   `App` conponent.I have done the Login.Vue but i don't know what to do to **render App.Vue** becuase their relation is not  *subroute*. Therefor i am confused about where to insert `<router-view>`.

**Comment by fundon** [comment]
I think that you should have a boolean variable likes `authenticated` to store the `login` or `logout`'s status, then use this `authenticated` to switch views.

**Comment by motecshine** [comment]
try vuex to manage your app status ,such as  login status ...

**Comment by fundon** [comment]
I closed it. If you still have issue, please re-open it.

**Comment by cpprookie** [comment]
@motecshine   Thanks  for  your  advice. I wonder if  i  can make  the  goal  without  vuex. Because  state  in  the  system  is  nit  too much.
