### ISSUE TITLE
[HELP] How to change global colors?

### ISSUE THREAD

**Issue by PhillippOhlandt** [fundon/vue-admin#73]
Hey,

I want to replace all the green colors, with blue colors. What is the best way to approach this?

**Comment by fundon** [comment]
See https://github.com/fundon/vue-admin/blob/master/client/App.vue#L57 and http://bulma.io/documentation/overview/start/.

**Comment by PhillippOhlandt** [comment]
Ah yeah, I always forget about the simple things. Overriding the `$primary` SASS variable did it 👍
