### ISSUE TITLE
npm run build  后，刷新会404的问题

### ISSUE THREAD

**Issue by cgkoreyoshi** [fundon/vue-admin#75]
npm run build  后放到服务器目录下，如果打开了某个菜单页面(不是首页)，比如，xxx.xxx.com/menu123/   刷新浏览器会404的问题，这个打包方案是不是决定了这个问题无法解决？求指导能支持在子页面刷新的方案

**Comment by fundon** [comment]
看这里 https://github.com/vuejs/vue-router/blob/dev/docs/zh-cn/essentials/history-mode.md，需要服务端作相应的配置。

**Comment by cgkoreyoshi** [comment]
哦，看了下，大概明白了，但是我这个项目由于某些java后台的原因，已经用掉了这条规则，还有什么办法可以解决吗
location / {
  try_files $uri $uri/ /index.html;
}

**Comment by motecshine** [comment]
@cgkoreyoshi  nginx vhost
