### ISSUE TITLE
您好, 請問如何載入自訂的 .css 檔案

### ISSUE THREAD

**Issue by imagine10255** [fundon/vue-admin#82]
您好, 請問如何載入自訂的 .css 檔案.
找不到方法 將自定義的 your_style.css 檔案載入
請教在這個模組上應該怎麼做比較適合呢 ？

放在 App.vue 載入 還是  index.js 呢 ?

PS: 這麼模組很棒

**Comment by fundon** [comment]
如果是自定义的全局样式，可以放在 `App.vue`，具体看 https://github.com/fundon/vue-admin/blob/master/client/App.vue#L51-L62。

如果是组件的样式就应该放在组件的 `style` 标签中。

**Comment by fundon** [comment]
另外也可以使用这种方式引入进来：`<style src="your_style.css">

**Comment by fundon** [comment]
我先关闭了，如果还有问题，请重新打开。谢谢。

**Comment by imagine10255** [comment]
請問 your_style.css 應該要放在哪個路徑下
使用<style src="your_style.css">。才 load 的到呢 ?
卡住很久試不出來.SORRY

**Comment by fundon** [comment]
可以在 `client` 目录下，创建一个 `css` 目录，存放这些自定义样式，那么这个 `src` 地址就可以使用文件的相对位置。

**Comment by imagine10255** [comment]
-----------------

import 報錯

![image](https://cloud.githubusercontent.com/assets/5771353/20030727/9dcf36b2-a3a5-11e6-9878-2e325d7968ec.png)

your_style.css 的內容只有這樣

![image](https://cloud.githubusercontent.com/assets/5771353/20030731/b9a6945c-a3a5-11e6-9f25-fdada5ec8aad.png)

在 webpack.base.conf.js 加上
![image](https://cloud.githubusercontent.com/assets/5771353/20030738/e4bdf374-a3a5-11e6-9d07-3a85383a0330.png)

**Comment by imagine10255** [comment]
您好, 上面說的那個方法有效, 非常感謝

> 可以在 client 目录下，创建一个 css 目录，存放这些自定义样式，那么这个 src 地址就可以使用文件的相对位置。

**Comment by imagine10255** [comment]
您好, 我遇到相同問題, 這次是要載入 test.js

一樣是在 App.vue 嗎 ?

我試過在 App.vue

    <script type="text/javascript" src="./assets/js/test.js"></script>

但是 vue 的 method 語法似乎失效了

![image](https://cloud.githubusercontent.com/assets/5771353/20036626/c08ae8fc-a447-11e6-9429-8a5a713d98e1.png)

![image](https://cloud.githubusercontent.com/assets/5771353/20036631/ccedead6-a447-11e6-8ab2-f1ad689c6997.png)

**Comment by luventa** [comment]
你可能是没有在vm中声明components
另外不建议使用这种方式去引入js模块，建议使用export/import，具体请参照ES6语法。
