### ISSUE TITLE
安装依赖库的时候碰到一个小问题

### ISSUE THREAD

**Issue by answord** [fundon/vue-admin#85]
使用npm install安装依赖库，最后npm run dev时报错，查看日志发现说vue版本mismatch什么的，发现vue安装的是2.0.3，而vue-template-compiler却是2.0.5的，github上查看vue的最新版本却是2.0.5，又回过头来看package.json才发现dependencies的vue版本写死为2.0.3，但devDependencies的vue-template-compiler版本却是^2.0.3。

虽然是小问题，为免后来者在此处浪费时间，建议改成一致的好。

**Comment by fundon** [comment]
谢谢提醒，已更新。
