### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by vetalball** [fundon/vue-admin#90]
Hello, @fundon 
It seems like you are building a great project, however I can't run it.
After `npm run dev` I got an error.
Please see attached [npm-debug.log.txt](https://github.com/fundon/vue-admin/files/580692/npm-debug.log.txt)
Could you please help me with this?

**Comment by fundon** [comment]
Hi, @vetalball Thank you for your feedback.

Do you run `npm install` before `npm run dev`?

**Comment by vetalball** [comment]
@fundon, yes

**Comment by fundon** [comment]
Try `node build/dev-server.js`

**Comment by vetalball** [comment]
After `node build/dev-server.js` the issue became more obvious. 
I had a problem with port listening. 
So I've changed it to 8082, and it worked!
Thank you so much for prompt replies!
