### ISSUE TITLE
依赖包不能加载

### ISSUE THREAD

**Issue by Leoxueping** [fundon/vue-admin#91]
我们做一个项时只有Linux可以正常运行，Mac报以下错误：
```
ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /Users/leon/Desktop/work/gospel/admin/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 
 @ ./~/.6.2.7@babel-loader!./~/.9.8.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-emoji/src/index.js
Module parse failed: /Users/leon/Desktop/work/gospel/admin/node_modules/.0.0.1@vue-bulma-emoji/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
| 
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.2.7@babel-loader!./~/.9.8.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.4@vue-bulma-progress-tracker/src/index.js
Module parse failed: /Users/leon/Desktop/work/gospel/admin/node_modules/.0.0.4@vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
| 
 @ ./~/.6.2.7@babel-loader!./~/.9.8.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 74:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

```

**Comment by fundon** [comment]
请问，使用的是 master 分支最新代吗？

**Comment by luventa** [comment]
看报错里面，用的是最新的。
错误像是loader报错。
我在担心，会不会是昨天我重构的有欠考虑？

另：Windows下build和dev是正常的

**Comment by fundon** [comment]
https://ci.appveyor.com/project/fundon/vue-admin 这里也没问题。

**Comment by fundon** [comment]
@Leoxueping 更新下第三方库，`npm up -d` 试试。

**Comment by wikidson** [comment]
我也遇到同样的问题，请问怎么解决啊

**Comment by wikidson** [comment]
ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /Users/wikid/outsourcing/vue-admin-master/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
|
 @ ./~/.6.2.7@babel-loader!./~/.9.8.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-emoji/src/index.js
Module parse failed: /Users/wikid/outsourcing/vue-admin-master/node_modules/.0.0.1@vue-bulma-emoji/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
|
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.2.7@babel-loader!./~/.9.8.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.4@vue-bulma-progress-tracker/src/index.js
Module parse failed: /Users/wikid/outsourcing/vue-admin-master/node_modules/.0.0.4@vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
|
 @ ./~/.6.2.7@babel-loader!./~/.9.8.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 76:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

**Comment by wikidson** [comment]
在mac环境中，执行 cnpm install , 然后 npm start dev 报错。。。。

**Comment by Leoxueping** [comment]
@fundon 解决了 运行这个
`rm -rf node_modules && npm install -d`

**Comment by Leoxueping** [comment]
@wikidson `rm -rf node_modules && npm install -d`

**Comment by zhengguozhu** [comment]
I met the same issue on Windown 10.
Env: node V6.9.1, npm 3.10.8.

**Comment by tolerious** [comment]
`npm install -d` not work.

**Comment by lizhongyi** [comment]
对 windows 用户太不友好了安装依赖很不清楚了，希望早些改善

**Comment by xgdgsc** [comment]
I also get this error after using cnpm. Running npm works.
